openapi: 3.0.0
info:
  title: Cafe & Barbershop SaaS API
  version: 1.0.0
  description: >
    API for managing orders, reservations, and users for cafes and barbershops.
    All endpoints require authentication unless otherwise noted.

servers:
  - url: https://api.saas-demo.com/v1

paths:
  /orders:
    post:
      summary: Create a new order
      tags: [Orders]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      productId: { type: string }
                      quantity: { type: integer }
                discountCode: { type: string }
                tip: { type: number }
      responses:
        "201":
          description: Order created successfully
        "400":
          description: Invalid input
        "401":
          description: Unauthorized
    get:
      summary: List all orders
      tags: [Orders]
      parameters:
        - in: query
          name: status
          schema:
            type: string
            enum: [open, closed, refunded]
      responses:
        "200":
          description: List of orders

  /orders/{orderId}:
    get:
      summary: Get order details
      tags: [Orders]
      parameters:
        - in: path
          name: orderId
          required: true
          schema: { type: string }
      responses:
        "200":
          description: Order details
        "404":
          description: Order not found
    put:
      summary: Update an open order
      tags: [Orders]
      parameters:
        - in: path
          name: orderId
          required: true
          schema: { type: string }
      responses:
        "200":
          description: Order updated
        "400":
          description: Invalid request
        "403":
          description: Cannot modify closed order
        "404":
          description: Order not found
    delete:
      summary: Cancel an open order
      tags: [Orders]
      parameters:
        - in: path
          name: orderId
          required: true
          schema: { type: string }
      responses:
        "200":
          description: Order cancelled
        "403":
          description: Cannot cancel closed order
        "404":
          description: Order not found

  /orders/{orderId}/payments:
    post:
      summary: Pay for an order
      tags: [Payments]
      parameters:
        - in: path
          name: orderId
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                method:
                  type: string
                  enum: [cash, card, gift_card]
                amount: { type: number }
                cardToken:
                  type: string
                  description: Required if method=card
      responses:
        "200":
          description: Payment successful, order closed
        "402":
          description: Payment failed
        "404":
          description: Order not found

  /reservations:
    post:
      summary: Create a reservation
      tags: [Reservations]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [customerId, serviceId, employeeId, appointmentTime]
              properties:
                customerId: { type: string }
                serviceId: { type: string }
                employeeId: { type: string }
                appointmentTime: { type: string, format: date-time }
      responses:
        "201":
          description: Reservation created
        "400":
          description: Invalid input
        "401":
          description: Unauthorized
    get:
      summary: List reservations
      tags: [Reservations]
      parameters:
        - in: query
          name: customerId
          schema: { type: string }
      responses:
        "200":
          description: List of reservations
        "404":
          description: No reservations found

  /users:
    post:
      summary: Create a new user (employee)
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, email, role, businessId]
              properties:
                name: { type: string }
                email: { type: string }
                role:
                  type: string
                  enum: [employee, owner, superadmin]
                businessId: { type: string }
      responses:
        "201":
          description: User created
        "400":
          description: Invalid user data
        "401":
          description: Unauthorized
        "403":
          description: Insufficient permissions

  /users/{userId}:
    put:
      summary: Update user details
      tags: [Users]
      parameters:
        - in: path
          name: userId
          required: true
          schema: { type: string }
      responses:
        "200":
          description: User updated
        "400":
          description: Invalid request
        "403":
          description: Insufficient permissions
        "404":
          description: User not found
    delete:
      summary: Delete a user
      tags: [Users]
      parameters:
        - in: path
          name: userId
          required: true
          schema: { type: string }
      responses:
        "200":
          description: User deleted
        "403":
          description: Insufficient permissions
        "404":
          description: User not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
