// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pos.Api.Context;

#nullable disable

namespace Pos.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251121143102_UpdatedOrderModels")]
    partial class UpdatedOrderModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("point_of_sale")
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pos.Api.Orders.Model.Order", b =>
                {
                    b.Property<Guid>("orderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("orderId");

                    b.Property<DateTime?>("closedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closedAt");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<Guid?>("customerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customerId");

                    b.Property<decimal>("discountAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("discountAmount");

                    b.Property<string>("registrationNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("registrationNumber");

                    b.Property<decimal>("serviceChargeAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("serviceChargeAmount");

                    b.Property<decimal>("serviceChargePct")
                        .HasColumnType("numeric")
                        .HasColumnName("serviceChargePct");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("subtotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("subtotalAmount");

                    b.Property<decimal>("taxAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("taxAmount");

                    b.Property<decimal>("tipAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("tipAmount");

                    b.Property<decimal>("totalDue")
                        .HasColumnType("numeric")
                        .HasColumnName("totalDue");

                    b.HasKey("orderId");

                    b.ToTable("Orders", "point_of_sale");
                });

            modelBuilder.Entity("Pos.Api.Orders.Model.OrderLine", b =>
                {
                    b.Property<Guid>("orderLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("orderLineId");

                    b.Property<Guid?>("appointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointmentId");

                    b.Property<Guid?>("assignedStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignedStaffId");

                    b.Property<string>("notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("orderId")
                        .HasColumnType("uuid")
                        .HasColumnName("orderId");

                    b.Property<Guid>("productId")
                        .HasColumnType("uuid")
                        .HasColumnName("productId");

                    b.Property<int>("quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("subTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("subTotal");

                    b.Property<decimal>("unitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unitPrice");

                    b.HasKey("orderLineId");

                    b.ToTable("OrderLines", "point_of_sale");
                });

            modelBuilder.Entity("Pos.Api.Orders.Model.OrderLineOption", b =>
                {
                    b.Property<Guid>("orderLineOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("orderLineOptionId");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("orderLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("orderLineId");

                    b.Property<string>("priceDelta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priceDelta");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("orderLineOptionId");

                    b.ToTable("OrderLineOptions", "point_of_sale");
                });

            modelBuilder.Entity("Pos.Api.Orders.Model.OrderLineTax", b =>
                {
                    b.Property<Guid>("orderLineTaxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("orderLineTaxId");

                    b.Property<Guid>("orderLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("orderLineId");

                    b.Property<decimal>("taxAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("taxAmount");

                    b.Property<string>("taxCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("taxCode");

                    b.Property<decimal>("taxPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("taxPercentage");

                    b.HasKey("orderLineTaxId");

                    b.ToTable("OrderLineTaxes", "point_of_sale");
                });

            modelBuilder.Entity("Pos.Api.taxes.model.Taxes", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("percentage")
                        .HasColumnType("numeric")
                        .HasColumnName("percentage");

                    b.HasKey("id");

                    b.ToTable("taxes", "point_of_sale");
                });
#pragma warning restore 612, 618
        }
    }
}
