// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pos.Api.Context;

#nullable disable

namespace Pos.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251215124913_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("point_of_sale")
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pos.Api.BusinessStaff.Models.Business", b =>
                {
                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("RegistrationNumber");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("CurrencyCode");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Email");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Phone");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("Type");

                    b.Property<string>("VatCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("VatCode");

                    b.HasKey("RegistrationNumber");

                    b.ToTable("Businesses", "point_of_sale");
                });

            modelBuilder.Entity("Pos.Api.BusinessStaff.Models.Staff", b =>
                {
                    b.Property<Guid>("staffId")
                        .HasColumnType("uuid")
                        .HasColumnName("StaffId");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Password");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Email");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("FirstName");

                    b.Property<DateTime>("hireDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("HireDate");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("LastName");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("PhoneNumber");

                    b.Property<string>("registrationNumber")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasColumnName("RegistrationNumber");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Role");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.HasKey("staffId");

                    b.HasIndex("registrationNumber");

                    b.ToTable("Staff", "point_of_sale");
                });

            modelBuilder.Entity("Pos.Api.Orders.Model.Order", b =>
                {
                    b.Property<Guid>("orderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("orderId");

                    b.Property<DateTime?>("closedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closedAt");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<Guid?>("customerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customerId");

                    b.Property<decimal>("discountAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("discountAmount");

                    b.Property<string>("registrationNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("registrationNumber");

                    b.Property<decimal>("serviceChargeAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("serviceChargeAmount");

                    b.Property<decimal>("serviceChargePct")
                        .HasColumnType("numeric")
                        .HasColumnName("serviceChargePct");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("subtotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("subtotalAmount");

                    b.Property<decimal>("taxAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("taxAmount");

                    b.Property<decimal>("tipAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("tipAmount");

                    b.Property<decimal>("totalDue")
                        .HasColumnType("numeric")
                        .HasColumnName("totalDue");

                    b.HasKey("orderId");

                    b.ToTable("Orders", "point_of_sale");
                });

            modelBuilder.Entity("Pos.Api.Orders.Model.OrderLine", b =>
                {
                    b.Property<Guid>("orderLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("orderLineId");

                    b.Property<string>("appointmentId")
                        .HasColumnType("text")
                        .HasColumnName("appointmentId");

                    b.Property<string>("assignedStaffId")
                        .HasColumnType("text")
                        .HasColumnName("assignedStaffId");

                    b.Property<string>("notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("orderId")
                        .HasColumnType("uuid")
                        .HasColumnName("orderId");

                    b.Property<Guid>("productId")
                        .HasColumnType("uuid")
                        .HasColumnName("productId");

                    b.Property<int>("quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("subTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("subTotal");

                    b.Property<decimal>("unitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unitPrice");

                    b.HasKey("orderLineId");

                    b.HasIndex("orderId");

                    b.ToTable("OrderLines", "point_of_sale");
                });

            modelBuilder.Entity("Pos.Api.Orders.Model.OrderLineOption", b =>
                {
                    b.Property<Guid>("orderLineOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("orderLineOptionId");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("orderLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("orderLineId");

                    b.Property<string>("priceDelta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priceDelta");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("orderLineOptionId");

                    b.ToTable("OrderLineOptions", "point_of_sale");
                });

            modelBuilder.Entity("Pos.Api.Orders.Model.OrderLineTax", b =>
                {
                    b.Property<Guid>("orderLineTaxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("orderLineTaxId");

                    b.Property<Guid>("orderLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("orderLineId");

                    b.Property<decimal>("taxAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("taxAmount");

                    b.Property<string>("taxCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("taxCode");

                    b.Property<decimal>("taxPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("taxPercentage");

                    b.HasKey("orderLineTaxId");

                    b.ToTable("OrderLineTaxes", "point_of_sale");
                });

            modelBuilder.Entity("Pos.Api.Products.model.Product", b =>
                {
                    b.Property<Guid>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("productId");

                    b.Property<decimal>("basePrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("basePrice");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int?>("durationMinutes")
                        .IsRequired()
                        .HasColumnType("integer")
                        .HasColumnName("durationMinutes");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("registrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("registrationNumber");

                    b.Property<bool>("status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<string>("taxCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("taxCode");

                    b.Property<int>("type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("productId");

                    b.ToTable("Products", "point_of_sale");
                });

            modelBuilder.Entity("Pos.Api.Products.model.ProductStaff", b =>
                {
                    b.Property<Guid>("productStaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("productStaffId");

                    b.Property<Guid>("productId")
                        .HasColumnType("uuid")
                        .HasColumnName("productId");

                    b.Property<Guid>("staffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staffId");

                    b.Property<bool>("status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<DateTime?>("valideFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valideFrom");

                    b.Property<DateTime?>("valideTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valideTo");

                    b.HasKey("productStaffId");

                    b.HasIndex("staffId");

                    b.HasIndex("productId", "staffId")
                        .IsUnique();

                    b.ToTable("ProductStaff", "point_of_sale");
                });

            modelBuilder.Entity("Pos.Api.reservations.model.Reservation", b =>
                {
                    b.Property<string>("AppointmentId")
                        .HasColumnType("text")
                        .HasColumnName("appointmentId");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customerId");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("durationMinutes");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employeeId");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OrderId")
                        .HasColumnType("text")
                        .HasColumnName("orderId");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("registrationNumber");

                    b.Property<string>("ServiceProductId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serviceProductId");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startTime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("AppointmentId");

                    b.ToTable("reservations", "point_of_sale");
                });

            modelBuilder.Entity("Pos.Api.taxes.model.Tax", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("percentage")
                        .HasColumnType("numeric")
                        .HasColumnName("percentage");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("taxes", "point_of_sale");
                });

            modelBuilder.Entity("Pos.Api.BusinessStaff.Models.Staff", b =>
                {
                    b.HasOne("Pos.Api.BusinessStaff.Models.Business", "Business")
                        .WithMany("StaffMembers")
                        .HasForeignKey("registrationNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Pos.Api.Orders.Model.OrderLine", b =>
                {
                    b.HasOne("Pos.Api.Orders.Model.Order", null)
                        .WithMany("Lines")
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Api.Products.model.ProductStaff", b =>
                {
                    b.HasOne("Pos.Api.Products.model.Product", "product")
                        .WithMany("EligibleStaff")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pos.Api.BusinessStaff.Models.Staff", "staff")
                        .WithMany("productAssignments")
                        .HasForeignKey("staffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("staff");
                });

            modelBuilder.Entity("Pos.Api.BusinessStaff.Models.Business", b =>
                {
                    b.Navigation("StaffMembers");
                });

            modelBuilder.Entity("Pos.Api.BusinessStaff.Models.Staff", b =>
                {
                    b.Navigation("productAssignments");
                });

            modelBuilder.Entity("Pos.Api.Orders.Model.Order", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Pos.Api.Products.model.Product", b =>
                {
                    b.Navigation("EligibleStaff");
                });
#pragma warning restore 612, 618
        }
    }
}
