// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pos.Api.Context;

#nullable disable

namespace Pos.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("point_of_sale")
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pos.Api.reservations.model.Reservation", b =>
            {
                b.Property<string>("AppointmentId")
                    .HasColumnType("text")
                    .HasColumnName("appointmentId");

                b.Property<string>("CustomerId")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("customerId");

                b.Property<int>("DurationMinutes")
                    .HasColumnType("integer")
                    .HasColumnName("durationMinutes");

                b.Property<string>("EmployeeId")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("employeeId");

                b.Property<string>("Notes")
                    .HasColumnType("text")
                    .HasColumnName("notes");

                b.Property<string>("OrderId")
                    .HasColumnType("text")
                    .HasColumnName("orderId");

                b.Property<string>("RegistrationNumber")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("registrationNumber");

                b.Property<string>("ServiceProductId")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("serviceProductId");

                b.Property<DateTime>("StartTime")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("startTime");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("status");

                b.HasKey("AppointmentId");

                b.ToTable("reservations", "point_of_sale");
            });

            modelBuilder.Entity("Pos.Api.BusinessStaff.Models.Business", b =>
            {
                b.Property<string>("RegistrationNumber")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<string>("CurrencyCode")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("character varying(3)");

                b.Property<string>("Email")
                    .HasColumnType("text");

                b.Property<string>("Location")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<string>("Phone")
                    .HasColumnType("text");

                b.Property<string>("VatCode")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.HasKey("RegistrationNumber");

                b.ToTable("Businesses", "point_of_sale");
            });

            modelBuilder.Entity("Pos.Api.BusinessStaff.Models.Staff", b =>
            {
                b.Property<int>("StaffId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StaffId"));

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<DateTime>("HireDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("PhoneNumber")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("RegistrationNumber")
                    .IsRequired()
                    .HasColumnType("character varying(50)");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("StaffId");

                b.HasIndex("RegistrationNumber");

                b.ToTable("Staff", "point_of_sale");
            });

            modelBuilder.Entity("Pos.Api.taxes.model.Taxes", b =>
            {
                b.Property<Guid>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("description")
                    .HasColumnType("text")
                    .HasColumnName("description");

                b.Property<string>("name")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("name");

                b.Property<decimal>("percentage")
                    .HasColumnType("numeric")
                    .HasColumnName("percentage");

                b.HasKey("id");

                b.ToTable("taxes", "point_of_sale");
            });

            modelBuilder.Entity("Pos.Api.BusinessStaff.Models.Staff", b =>
            {
                b.HasOne("Pos.Api.BusinessStaff.Models.Business", "Business")
                    .WithMany("StaffMembers")
                    .HasForeignKey("RegistrationNumber")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Business");
            });

            modelBuilder.Entity("Pos.Api.BusinessStaff.Models.Business", b =>
            {
                b.Navigation("StaffMembers");
            });
#pragma warning restore 612, 618
        }
    }
}
